### ISSUE TITLE
Update for 2.0?

### ISSUE THREAD

**Issue by manierim** [raiguard/MouseOverConstruction#14]
First of all thanks for all the wonderful mods you make available for us.
Many have already been updated to 2.0 but not this. 
Hope it is planned as well?

**Comment by raiguard** [comment]
I only have so much time. I have to prioritize my Wube work and then the next priority is Krastorio 2. So it might be a while.

**Comment by target-san** [comment]
Do you accept PRs?

**Comment by raiguard** [comment]
I do, but for something like this it will be more efficient if I just do it myself. I can update the mod myself far quicker than I can comb through someone else's code doing the same.

**Comment by Kamsta99** [comment]
Really waiting for 2.0 version, building early game now via hand is really pain

**Comment by target-san** [comment]
@raiguard

I almost ported stuff - except quality 😁

My two main issues so far
1. It seems that if entity is being upgraded to the same prototype with different quality, `to_be_upgraded` returns `false` and `get_upgrade_target` returns `nil, nil`
2. There's `ghost_prototype` but no `ghost_quality`. Not sure how to deal with `entity-ghost` cases

Or am I doing something utterly wrong?

**Comment by raiguard** [comment]
Sorry for missing your PR, I just pushed my own update. Oh well. :laughing:
