### ISSUE TITLE
Forced shutdown in navigation system mode

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [raiguard/MouseOverConstruction#4]
In the Space Exploration mode, there is a navigation system mode when a free camera is controlled with the ability to change the settings of existing buildings and arrange construction plans. In this mode, the enabled MouseOverConstruction is hindered by the fact that the camera freezes if the cursor is pointed at a ghost and an attempt is made to build or break it.

Is it possible to make MouseOverConstruction forcibly disabled or unavailable at all when switching to navigation mode?

**Comment by raiguard** [comment]
I can't reproduce this "freezing" behavior, can you post exact reproduction steps?

**Comment by Eldrinn-Elantey** [comment]
I must have expressed myself incorrectly. If MouseOverConstruction is enabled and you are in the navigation system mode, then when you hover the cursor over the object marked for dismantling, an attempt to execute it will begin (a performance bar will appear above the hotbar), but this will not happen due to the lack of such an opportunity for the navigation system. While there will be an attempt to move using the keys, it will be impossible while the cursor is over the object marked for dismantling.

**Comment by raiguard** [comment]
I don't think it's worth adding a bunch of logic to detect the SE navsat vs. regular god mode. If you're in navsat then remember to disable the mod.
