### ISSUE TITLE
Assemblers blueprinted to request 1 module request 2 when placed with mouse-over

### ISSUE THREAD

**Issue by rpdelaney** [raiguard/MouseOverConstruction#6]
### Description

When using mouse-over to place a ghost assembler from blueprint, if the blueprinted assembler requests 1 module to be inserted, 2 are requested in the new assembler.

Base mod version: 1.1.87
Mouse-over construction version: 1.2.0

### Reproduction

1. Place a blue assembler. Insert one module and leave the other slot empty.
2. Copy the assembler and paste.
3. Mouse over the assembler.
4. Manually insert the module as with the other assembler. (see #5)
5. Observe that the assembler still requests modules to be inserted.

**Comment by raiguard** [comment]
This is a base game behavior. I will see if we can fix it for Factorio 2.0, because it ought to account for manually inserted modules.
